plugins {
  id 'base'
}

allprojects {
  group = 'com.luokuiai.forga'
  version = '1.0.0-SNAPSHOT'

  repositories {
    mavenCentral()
  }
}

subprojects {
  apply plugin: 'java-library'
  apply plugin: 'checkstyle'

  java {
    toolchain {
      languageVersion = JavaLanguageVersion.of(17)
    }
    withSourcesJar()
  }

  dependencies {
    testImplementation platform('org.junit:junit-bom:5.11.4')
    testImplementation 'org.junit.jupiter:junit-jupiter'
    testImplementation 'org.assertj:assertj-core:3.27.3'
  }

  tasks.withType(JavaCompile).configureEach {
    options.encoding = 'UTF-8'
    options.compilerArgs += ['-Xlint:all', '-Werror']
  }

  tasks.withType(Test).configureEach {
    useJUnitPlatform()
  }

  checkstyle {
    toolVersion = '10.23.1'
    configFile = rootProject.file('gradle/checkstyle/checkstyle.xml')
  }
}
