dependencies {
  api project(':forga-core')
  api project(':forga-query')
  api project(':forga-mybatis')
  api project(':forga-spring-web')
  compileOnly 'org.springframework.boot:spring-boot-autoconfigure:3.5.16'
  compileOnly 'com.baomidou:mybatis-plus-extension:3.5.17'
  testImplementation 'com.baomidou:mybatis-plus-extension:3.5.17'
}
