dependencies {
  api project(':forga-core')
  compileOnly 'jakarta.annotation:jakarta.annotation-api:3.0.0'
  compileOnly 'jakarta.servlet:jakarta.servlet-api:6.0.0'
  compileOnly "org.springframework:spring-webmvc:${springFrameworkVersion}"
  testImplementation 'jakarta.annotation:jakarta.annotation-api:3.0.0'
  testImplementation 'jakarta.servlet:jakarta.servlet-api:6.0.0'
  testImplementation "org.springframework:spring-webmvc:${springFrameworkVersion}"
  testImplementation "org.springframework:spring-test:${springFrameworkVersion}"
}
